services:
    nestjs_api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
        depends_on:
            - mysql
        volumes:
            - ./src:/app/src
            - ./public:/app/public

    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=nestjs_db
            - MYSQL_USER=nestjs_user
            - MYSQL_PASSWORD=password
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        cap_add:
            - SYS_NICE

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '3002:80'
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_ARBITRARY=1
            - MYSQL_ROOT_PASSWORD=password
        depends_on:
            - mysql

volumes:
    mysql_data:
